### ISSUE TITLE
eth_call   WARNING: Calling an account which is not a contract

### ISSUE THREAD

**Issue by Sunil6591** [scaffold-eth/scaffold-eth#641]
**Describe the bug**
hey guys!! m beginner here, using the clone , the `setPurpose` function works and i see the transaction on hardhat node terminal. However when i call get it gives me 
```
eth_call
  WARNING: Calling an account which is not a contract
```
and on UI it gives - 
```
Error:  Error: call revert exception (method="purpose()", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.0.7)
    at Logger.makeError (ethers.umd.js:5701:1)
    at Logger.throwError (ethers.umd.js:5710:1)
    at Interface.decodeFunctionResult (ethers.umd.js:11192:1)
    at Contract.<anonymous> (ethers.umd.js:12290:1)
    at step (ethers.umd.js:12017:1)
    at Object.next (ethers.umd.js:11998:1)
    at fulfilled (ethers.umd.js:11989:1)  
```
if the calling account is not my contract, then how come the set function is working

**To Reproduce**
1. Run the web app
2. Click on Set purpose
3. Now try to get the purpose
4. See error in browser console

**Expected behavior**
App should display the newly set purpose.

**Comment by Sunil6591** [comment]
I got the above fixed by using below sequence 
`npx hardhat node`
`npx hardhat run --network localhost scripts/deploy.js`
so in short you need to mention the network while deploying the contract
