### ISSUE TITLE
insufficient funds for intrinsic transaction cost

### ISSUE THREAD

**Issue by tony123S** [scaffold-eth/scaffold-eth#941]
I switch network from local to Mumbai, but get this error when I enter yarn deploy

```
PS C:\Users\nick_\VSCodeProjects\scaffold-eth> yarn deploy
yarn run v1.22.19
$ yarn workspace @scaffold-eth/hardhat deploy
$ hardhat deploy --export-all ../react-app/src/contracts/hardhat_contracts.json
Nothing to compile
deploying "YourContract"insufficient funds for intrinsic transaction cost (error={"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at HttpProvider.request (C:\\Users\\nick_
\\VSCodeProjects\\scaffold-eth\\packages\\hardhat\\node_modules\\hardhat\\src\\internal\\core\\providers\\http.ts:78:19)\n    at HDWalletProvider.request (C:\\Users\\nick_\\VSCodeProjects\\scaff
old-eth\\packages\\hardhat\\node_modules\\hardhat\\src\\internal\\core\\providers\\accounts.ts:181:36)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","code":-32000,"
_isProviderError":true}, method="sendTransaction", transaction=undefined, code=INSUFFICIENT_FUNDS, version=providers/5.4.4) {"reason":"insufficient funds for intrinsic transaction cost","code":"
INSUFFICIENT_FUNDS","error":{"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at HttpProvider.request (C:\\Users\\nick_\\VSCodeProjects\\scaffold-eth\\packages\\hardhat\\no
de_modules\\hardhat\\src\\internal\\core\\providers\\http.ts:78:19)\n    at HDWalletProvider.request (C:\\Users\\nick_\\VSCodeProjects\\scaffold-eth\\packages\\hardhat\\node_modules\\hardhat\\sr
c\\internal\\core\\providers\\accounts.ts:181:36)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","code":-32000,"_isProviderError":true},"method":"sendTransaction"} E
rror: insufficient funds for intrinsic transaction cost (error={"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at HttpProvider.request (C:\\Users\\nick_\\VSCodeProjects\\
scaffold-eth\\packages\\hardhat\\node_modules\\hardhat\\src\\internal\\core\\providers\\http.ts:78:19)\n    at HDWalletProvider.request (C:\\Users\\nick_\\VSCodeProjects\\scaffold-eth\\packages\
\hardhat\\node_modules\\hardhat\\src\\internal\\core\\providers\\accounts.ts:181:36)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","code":-32000,"_isProviderError":
true}, method="sendTransaction", transaction=undefined, code=INSUFFICIENT_FUNDS, version=providers/5.4.4)
    at Logger.makeError (C:\Users\nick_\VSCodeProjects\scaffold-eth\packages\hardhat\node_modules\@ethersproject\logger\src.ts\index.ts:213:28)
    at Logger.throwError (C:\Users\nick_\VSCodeProjects\scaffold-eth\packages\hardhat\node_modules\@ethersproject\logger\src.ts\index.ts:225:20)
    at checkError (C:\Users\nick_\VSCodeProjects\scaffold-eth\packages\hardhat\node_modules\hardhat-deploy\node_modules\@ethersproject\providers\src.ts\json-rpc-provider.ts:53:16)
    at C:\Users\nick_\VSCodeProjects\scaffold-eth\packages\hardhat\node_modules\hardhat-deploy\node_modules\@ethersproject\providers\src.ts\json-rpc-provider.ts:215:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'insufficient funds for intrinsic transaction cost',
  code: 'INSUFFICIENT_FUNDS',
  error: ProviderError: HttpProviderError
      at HttpProvider.request (C:\Users\nick_\VSCodeProjects\scaffold-eth\packages\hardhat\node_modules\hardhat\src\internal\core\providers\http.ts:78:19)
      at HDWalletProvider.request (C:\Users\nick_\VSCodeProjects\scaffold-eth\packages\hardhat\node_modules\hardhat\src\internal\core\providers\accounts.ts:181:36)
      at processTicksAndRejections (node:internal/process/task_queues:96:5),
  method: 'sendTransaction',
  transaction: undefined
}
An unexpected error occurred:
```

I have lower the gas fees in constant.js, but why still hitting this exception? 

```
  mumbai: {
    name: "mumbai",
    color: "#92D9FA",
    chainId: 80001,
    price: 1,
    gasPrice: 0.00001,
    rpcUrl: "https://rpc-mumbai.maticvigil.com",
    faucet: "https://faucet.polygon.technology/",
    blockExplorer: "https://mumbai.polygonscan.com/",
  },
```

**Comment by tony123S** [comment]
There are 0.89 MATIC in my metamask wallet.
